import os
import json
import vertexai
from vertexai.generative_models import GenerativeModel, Part

# Configuration
MODEL_NAME = "gemini-2.5-pro"
PROJECT_ID = os.environ.get("GCP_PROJECT_ID")
LOCATION = "us-central1"

if PROJECT_ID:
    try:
        vertexai.init(project=PROJECT_ID, location=LOCATION)
    except Exception as e:
        print(f"WARNING: Vertex AI init failed (ignore if local without creds): {e}")

async def analyze_video_native(video_gcs_uri: str, audio_transcript: str) -> list:
    """
    V5 FR-02: Sends the video URI and audio transcript directly to Gemini 2.5 Pro.
    Returns a list of dictionaries (ActionNodes) generated by the AI.
    """
    if not PROJECT_ID:
        raise ValueError("GCP_PROJECT_ID not set. Cannot call Vertex AI.")

    model = GenerativeModel(
        MODEL_NAME,
        generation_config={
            "temperature": 0.0, 
            "max_output_tokens": 8192, 
            "response_mime_type": "application/json"
        }
    )

    video_part = Part.from_uri(
        uri=video_gcs_uri,
        mime_type="video/mp4"
    )

    # Master Prompt: Includes audio for contextual fusion (FR-02)
    prompt = f"""
    You are an expert software documentation agent. Analyze this video and its audio.

    Audio Transcript: '{audio_transcript}'

    Using the audio and video cues, extract a structured timeline of user actions.
    
    Output a valid JSON array of objects. For each step, provide:
    1. "timestamp": The exact time (in seconds) the action occurs.
    2. "action_type": One of [click, type, scroll, drag, navigation].
    3. "target_text": The visible text or element (e.g., "Personalize") being interacted with.
    4. "description": A precise, human-readable sentence explaining WHAT the user did and WHY (based on visual and audio context).

    Strictly adhere to the JSON format.
    """

    try:
        response = await model.generate_content_async([video_part, prompt])
        raw_text = response.text.strip()
        steps = json.loads(raw_text)
        return steps

    except Exception as e:
        print(f"V5 Native Video Analysis Failed: {e}")
        return []